docker-compose-yaml: docker-compose.yml

project: 2019-texascamp

tasks:
  post-rollout:
    - run:
        name: drush updb
        command: cd web && drush -y updb --cache-clear=0
        service: cli
    - run:
        name: drush cim
        command: cd web && drush -y cim
        service: cli
    - run:
        name: drush cr
        command: cd web && drush -y cr
        service: cli

environments:
  prod:
    routes:
      - varnish:
        - backend2019.texascamp.org
      - frontend:
        - "texascamp.org":
            tls-acme: 'true'
            insecure: Redirect
        - "www.texascamp.org":
            tls-acme: 'true'
            insecure: Redirect
        - "2019.texascamp.org":
            tls-acme: 'true'
            insecure: Redirect
    cronjobs:
      - name: drush cron
        schedule: "H/15 * * * *"
        command: drush cron
        service: cli